
name: build

on: 
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - name: Set up uv
        uses: astral-sh/setup-uv@v7
      - name: Install stewbeet
        run: |
          uv venv
          uv pip install --pre stewbeet
      - name: Setup OpenGL and Build project
        uses: edayot/model_resolver@master
        with:
          commands: |
            uv run stewbeet rebuild
      - name: Save build artifacts
        run: |
          cp -r build /tmp/build
          cp -r manual_cache /tmp/manual_cache
      
      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Create orphan build branch
        run: |
          git checkout --orphan build
      
      - name: Clear working directory
        run: |
          git rm -rf .
          rm -rf *
      
      - name: Restore build artifacts
        run: |
          cp -r /tmp/build .
          cp -r /tmp/manual_cache .
      
      - name: Commit changes
        run: |
          git add build/ manual_cache/
          git commit -m "Build from ${{ github.ref_name }}"
      
      - name: Push to build branch
        run: |
          git push -f origin build
